import "../style.css";

export default function WhatIsRoi() {
  return (
    <div
      className="blog-page-container"
    >
      {/* actual blog */}
      <div
        className="blog-content"
      >
        <div>
          <h2 className="blog-heading">
            What is return on investment (ROI)? How do you measure it?
          </h2>
          <div>{/* img + Name + Date */}</div>
        </div>

        {/* image */}
        <div>{/* Featured Image */}</div>

        {/* Content */}
        <div>
          <p>
            A website gets more traffic through organic search, almost more than
            half of it. It is very important that your website be excellent in
            <strong> search engine optimization </strong>
            and meet all the little to big criteria. The important part is to
            evaluate the website ranking progress thoroughly.
          </p>

          <p>
            More traffic means more revenue, and
            <strong> measuring the ROI of SEO </strong>
            can give you a clear picture of the future potential of your
            website, how much revenue it will create, and how effectively it is
            running on search engines. ROI serves as a report card of your
            website’s performance.
          </p>

          <p>
            After finishing reading this article, you will have a clear picture
            of how to calculate ROI, what ROI is, and how to communicate SEO ROI
            to your potential clients, or you can contact us; we are always
            ready to guide you. We are the digital marketing agency in Andheri
            East, Mumbai, India.
          </p>

          <h2
            id="how-to-measure-seo-roi"
            style={{ fontSize: "24px", fontWeight: 600, marginTop: "30px" }}
          >
            How to measure SEO ROI
          </h2>

          {/* ROI Formula Image */}
          <div>{/* ROI Formula Image */}</div>

          <h2
            id="why-does-seo-roi-matter-for-the-business"
            style={{ fontSize: "24px", fontWeight: 600, marginTop: "30px" }}
          >
            Why does SEO ROI matter for the business?
          </h2>

          <p>
            The ROI of SEO is a calculation that shows the result of actual
            revenue a business generates through SEO activities compared to the
            cost that has been invested in SEO. A key performance indicator
            (KPI) is essential to measure because it ties your SEO efforts to
            business goals.
          </p>

          <p>
            Always keep in mind that for a successful business run, your net
            revenue generated by ROI SEO must be higher than its cost.
          </p>

          <p>
            For example, if the total SEO cost was $2000 and revenue generated
            from SEO was $5000, then the ROI is 150%. On the other hand, SEO
            ROI performance also depends on multiple factors such as the type of
            industry, the competition level of your business, website history,
            SEO strategy and plans, and every little to big thing that has to be
            noticed and worked on properly.
          </p>

          <p>
            We know that SEO is the big reason for attracting huge organic
            traffic on websites, and the organic traffic not only brings
            visitors but also represents monetary value.
          </p>

          <h3 style={{ fontSize: "20px", fontWeight: 600 }}>
            How It Works
          </h3>

          <ul>
            <li>
              Enter the estimated number of visitors your website is expected to
              receive each month.
            </li>

            <li>
              Add your website’s average ranking position in Google organic
              search results.
            </li>

            <li>
              Enter your website’s conversion rate, the percentage of visitors
              who complete a desired action, such as filling out an enquiry
              form, making a phone call, or submitting a contact request.
              Typically, this rate falls between 5 and 10%.
            </li>

            <li>
              Add your sales conversion rate — the percentage of leads that
              successfully convert into paying customers, clients, or patients.
            </li>

            <li>
              Enter your customer lifetime value — the average revenue your
              business expects to earn from a customer throughout the entire
              relationship.
            </li>
          </ul>

          <h2
            id="why-is-calculating-the-roi-of-seo-crucial"
            style={{ fontSize: "24px", fontWeight: 600, marginTop: "30px" }}
          >
            Why is calculating the ROI of SEO crucial?
          </h2>

          <p>
            Organic search is one of the biggest sources of website traffic, and
            today, most purchasing decisions involve organic search in some way.
          </p>

          <p>
            Since SEO plays such a major role in driving traffic and potential
            customers, understanding its financial value is essential for every
            business.
          </p>

          <p>
            Here are some key reasons why measuring SEO ROI is important:
          </p>

          <h3 style={{ fontSize: "20px", fontWeight: 600 }}>
            Communicating Success
          </h3>

          <p>
            While tracking SEO KPIs such as rankings, traffic, and backlinks is
            important, the ultimate indicator of success is a positive return on
            investment. Demonstrating strong SEO ROI makes it easier to prove
            the effectiveness of your strategy and gain trust and support from
            stakeholders or clients.
          </p>

          <h3 style={{ fontSize: "20px", fontWeight: 600 }}>
            Better Resource Allocation
          </h3>

          <p>
            Measuring SEO ROI helps identify which strategies and tactics are
            delivering the best results and which ones are underperforming. This
            allows businesses to allocate their time, budget, and resources more
            effectively.
          </p>

          <h3 style={{ fontSize: "20px", fontWeight: 600 }}>
            Competitive Benchmarking
          </h3>

          <p>
            Tracking SEO ROI alongside competitor analysis helps businesses
            understand whether they are outperforming competitors or falling
            behind. These insights help shape future SEO strategies and maintain
            a competitive advantage in the market.
          </p>

          <h2
            id="key-difficulties-in-tracking-seo"
            style={{ fontSize: "24px", fontWeight: 600, marginTop: "30px" }}
          >
            Key difficulties in tracking SEO
          </h2>

          <p>
            Consumer interests are changing constantly with time, and that is
            why it is difficult to maintain better SEO all the time. You have to
            develop and change the strategy of SEO according to time and the
            demand of the consumers. SEO is amazingly variable, so there are no
            guarantees.
          </p>

          <p>
            Nothing is guaranteed in the world of search engine optimization;
            you work hard on SEO and have hope of ranking in the top 10 search
            suggestions on the first page of the search engine and being on the
            first page at least. But nothing is promised, because like you,
            everyone is constantly working hard on SEO to be ranked on the first
            page.
          </p>

          <p>
            Competition is vast; that is why you have to be more flexible on
            learning and making SEO right. It is hard to know if the SEO efforts
            are actually working and harder to know how those changes will
            affect your ROI (return on investment).
          </p>

          <h2
            id="branded-and-non-branded-keywords"
            style={{ fontSize: "24px", fontWeight: 600, marginTop: "30px" }}
          >
            Branded and non-branded keywords
          </h2>

          <p>
            Keywords are crucial when it comes to ranking on the first page of a
            search engine; we all know that, but do you know there are branded
            and non-branded keywords too?
          </p>

          <p>
            Branded keywords are those that show the direct name of your company
            and services the company is providing. For example, “Tzar Venture
            Digital Blog on ROI” is a branded keyword because it is showing who
            is representing the blog and what the nature of the blog is and what
            kind of information you will get through this.
          </p>

          <p>
            On the other hand, non-branded keywords are those words or groups of
            words that describe the rest of the blog; they are like secondary
            keywords, general keyword types in SEO by audience, on a regular
            basis.
          </p>

          <p>
            Such as how to optimize a website for SEO, what ROI is, and the best
            restaurant for biryani. Here, no specific brand or company name is
            mentioned.
          </p>
        </div>
      </div>

      {/* fixed */}
      <div
        className="blog-sidebar"
      >
        <div
          style={{
            backgroundColor: "white",
            border: "1px solid #ebebeb",
            borderRadius: "10px",
            padding: "20px",
          }}
        >
          <div>
            <p>Table of Contents</p>
          </div>

          <div>
            <ul style={{ color: "gray" }}>
              <li>
                <a
                  href="#how-to-measure-seo-roi"
                  style={{ color: "gray" }}
                >
                  How to measure SEO ROI
                </a>
              </li>

              <li>
                <a
                  href="#why-does-seo-roi-matter-for-the-business"
                  style={{ color: "gray" }}
                >
                  Why does SEO ROI matter for the business?
                </a>
              </li>

              <li>
                <a
                  href="#why-is-calculating-the-roi-of-seo-crucial"
                  style={{ color: "gray" }}
                >
                  Why is calculating the ROI of SEO crucial?
                </a>
              </li>

              <li>
                <a
                  href="#key-difficulties-in-tracking-seo"
                  style={{ color: "gray" }}
                >
                  Key difficulties in tracking SEO
                </a>
              </li>

              <li>
                <a
                  href="#branded-and-non-branded-keywords"
                  style={{ color: "gray" }}
                >
                  Branded and non-branded keywords
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}